import os
import sys

from flask import (current_app, render_template, url_for, jsonify, request, session, abort, send_from_directory, Response, redirect)


def render():
    netmig_bp = current_app.blueprints.get("netmig")

    if netmig_bp.scripts_db:
        first_script_id = next(iter(netmig_bp.scripts_db))
        return redirect(url_for("netmig.render_script", script_id=first_script_id))

    kwargs = {
        "breadcrumbs": [
            {"title": "NetMig", "url": url_for("netmig.render")},
            {"title": "Home"}
        ],
    }
    return render_template("netmig.html", **kwargs)


def render_script(script_id):
    netmig_bp = current_app.blueprints.get("netmig")
    script_data = netmig_bp.scripts_db.get(script_id)

    if not script_data:
        abort(404)

    kwargs = {
        "breadcrumbs": [
            {"title": "NetMig", "url": url_for("netmig.render")},
            {"title": script_data.get("name", "Unknown Script")},
        ],
        "scripts": netmig_bp.scripts,
        "script_data": script_data,
        "input_html": netmig_bp.runner.scripts[script_id].input()
    }
    return render_template("netmig.runner.html", **kwargs)


def scan_scripts():
    """Scans the scripts directory for available scripts, loads their metadata, and returns a list of scripts with their details."""
    netmig_bp = current_app.blueprints["netmig"]
    netmig_bp.load_scripts()
    return jsonify(netmig_bp.scripts)


def list_script_outputs(script_id):
    """
    Lists the output files generated by a specific script, allowing users to download them.
    """
    base_dir = session["userdata"].get("reports_dir")
    script_dir = os.path.join(base_dir, script_id)

    if not os.path.isdir(script_dir):
        return jsonify([])

    rows = []

    for fname in os.listdir(script_dir):
        path = os.path.join(script_dir, fname)
        if not os.path.isfile(path):
            continue

        rows.append({
            "filename": fname
        })

    return jsonify(rows)


def stream_script_output(task_id):
    """
    Streams the real-time output of a running script task using Server-Sent Events (SSE).
    """
    netmig_bp = current_app.blueprints.get("netmig")
    return Response(
        netmig_bp.runner.stream_output(task_id),
        mimetype="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        }
    )


def download_script_output(script_id, filename):
    """
    Allows users to download a specific output file generated by a script.
    """
    base_dir = session["userdata"].get("reports_dir")
    script_dir = os.path.join(base_dir, script_id)

    return send_from_directory(
        script_dir,
        filename,
        as_attachment=True
    )


def run_script(script_id):
    """
    Executes a specified script with given inputs and configuration, and manages the output generation.
    """
    netmig_bp = current_app.blueprints.get("netmig")
    script = netmig_bp.scripts_db.get(script_id)
    if not script:
        abort(404)

    data = request.get_json(force=True)

    output_dir = os.path.join(session["userdata"].get("reports_dir"), script_id)
    os.makedirs(output_dir, exist_ok=True)

    task_params = {
        "script_id": script_id,
        "inputs": data.get("inputs", {}),
        "config": data.get("config", {}),
        "output_dir": output_dir
    }

    task = netmig_bp.runner.create_task(**task_params)
    netmig_bp.runner.run(task)

    return jsonify({"task_id": task})


def get_script_info(script_id):
    """
    Retrieves detailed information about a specific script, including its README content if available.
    """
    netmig_bp = current_app.blueprints.get("netmig")
    script = netmig_bp.scripts_db.get(script_id)
    if not script:
        abort(404)

    readme_path = os.path.join(script["path"], "README.md")
    readme_content = ""
    if os.path.exists(readme_path):
        with open(readme_path, "r") as f:
            readme_content = f.read()

    return jsonify({
        "readme": readme_content
    })